/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as PosRouteImport } from './routes/pos'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CashRouteImport } from './routes/cash'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as IndexRouteImport } from './routes/index'

const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/cash': typeof CashRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/cash': typeof CashRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/cash': typeof CashRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/pos': typeof PosRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/cash'
    | '/customers'
    | '/inventory'
    | '/pos'
    | '/purchases'
    | '/reports'
    | '/services'
    | '/settings'
    | '/work-orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/cash'
    | '/customers'
    | '/inventory'
    | '/pos'
    | '/purchases'
    | '/reports'
    | '/services'
    | '/settings'
    | '/work-orders'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/cash'
    | '/customers'
    | '/inventory'
    | '/pos'
    | '/purchases'
    | '/reports'
    | '/services'
    | '/settings'
    | '/work-orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRoute
  CashRoute: typeof CashRoute
  CustomersRoute: typeof CustomersRoute
  InventoryRoute: typeof InventoryRoute
  PosRoute: typeof PosRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  WorkOrdersRoute: typeof WorkOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRoute,
  CashRoute: CashRoute,
  CustomersRoute: CustomersRoute,
  InventoryRoute: InventoryRoute,
  PosRoute: PosRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  WorkOrdersRoute: WorkOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
